### ISSUE TITLE
sv_team 0 in autoexec.cfg

### ISSUE THREAD

**Issue by Matqyou** [ddnet/ddnet7#100]
For me its still 1 when the server is running.
And the map doesn't have any server commands.
I think this is a bug.

**Comment by ZombieToad** [comment]
sv_team is a map config option and will reset every time a map is loaded so you should set sv_team 0 on map config or set sv_ddrace_tune_reset 0

**Comment by def-** [comment]
The more you know. I noticed the same on DDNet6 :D

**Comment by fokkonaut** [comment]
I knew this since forever, tried to fix it but never got anything good

**Comment by Matqyou** [comment]
sv_practice works and its in variables.h but sv_team isn't

**Comment by fokkonaut** [comment]
@def- i would suggest removing the ddrace tune reset option, since it doesnt even include all ddrace options
