### ISSUE TITLE
Flappy Bird map not working properly?

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet7#28]
As reported by TEINI94:

> may just check out solo map flappy bird (u can finish it in 17sec if u know how) and

**Comment by fokkonaut** [comment]
There are tune changes inside of the map settings. They somehow dont get applied. I can look into that tomorrow, or if anyone else wants to do so go ahead. Maybe I forgot something while i was implementing map settings, other commands at least work. Maybe its also the quotes around, we'll see.
