### ISSUE TITLE
Add sv_rcon_helper_password

### ISSUE THREAD

**Issue by trafilaw** [ddnet/ddnet7#52]
Hey,

it would be awesome if not only Admin & Mod has permission to F2(rcon).
DDNet has the option too so I would like to use the option in DDNet7 *-*

**Comment by fokkonaut** [comment]
@Learath2 didnt you add helper? And didnt I fix the missing stuff for it?

**Comment by fokkonaut** [comment]
We had it in, but it seems like it bugged away? @Learath2 
I remember you added it and I fixed the missing things for it, but now the whole authmanager is gone...?

**Comment by trafilaw** [comment]
So is there anyway to add it again?

**Comment by fokkonaut** [comment]
Of course, someone just has to do it.
