### ISSUE TITLE
Unpredictable behaviour when holding input and hitting an unfreeze

### ISSUE THREAD

**Issue by 0xcny** [ddnet/ddnet7#53]
Holding hook while frozen and hitting an unfreeze sometimes doesn't trigger a hook. I don't know what determins it. Also unfreezes right above a freezetiles on the ground are buggy as well. Even with small speed holding jump won't always yield in a jump after the unfreeze and you just fall through. This is quite heavily impacting gameplay. :(

I attached a screen of a part that I failed 2/3 times even though I held jump and had 5 tiles down speed at max. So a jump should always register there.
![screenshot_2020-01-10_06-11-11](https://user-images.githubusercontent.com/34349467/72128767-382e4200-3374-11ea-9817-6fcc06b7f20f.png)

**Comment by fokkonaut** [comment]
I guess its the missing freeze input fix in ddnet7
