### ISSUE TITLE
Lots of crashes in gameworld.h:42

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet7#62]
```
Core was generated by `./DDNet7-Server -f servers/9304.cfg'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055d5377fd8f2 in CProjectile::CProjectile (this=0x55d538fb2950, pGameWorld=<optimized out>, Type=2, 
    Owner=-1, Pos=..., Dir=..., Span=-2, Freeze=<optimized out>, Explosive=false, Force=0, SoundImpact=6, Layer=0, 
    Number=0) at /home/teeworlds/src7/master/src/game/server/gameworld.h:42
42		class CGameContext *GameServer() { return m_pGameServer; }
[Current thread is 1 (Thread 0x7fa6cb3bf980 (LWP 18682))]
(gdb) bt
#0  0x000055d5377fd8f2 in CProjectile::CProjectile (this=0x55d538fb2950, pGameWorld=<optimized out>, Type=2, 
    Owner=-1, Pos=..., Dir=..., Span=-2, Freeze=<optimized out>, Explosive=false, Force=0, SoundImpact=6, Layer=0, 
    Number=0) at /home/teeworlds/src7/master/src/game/server/gameworld.h:42
#1  0x000055d53780bd00 in IGameController::OnEntity (this=0x55d538ff4170, Index=34, Pos=..., Layer=0, 
    Flags=<optimized out>, Number=0) at /home/teeworlds/src7/master/src/game/server/entity.h:17
#2  0x000055d537805659 in CGameContext::OnInit (this=0x7fa6ca202010)
    at /home/teeworlds/src7/master/src/game/server/gamecontext.cpp:2213
#3  0x000055d5377e4819 in CServer::Run (this=0x7fa6caa33010)
    at /home/teeworlds/src7/master/src/engine/server/server.h:83
#4  0x000055d5377dbd4e in main (argc=3, argv=0x7fff0c84bf48)
    at /home/teeworlds/src7/master/src/engine/server/server.cpp:2386
```
Seems to happen a lot on all DDNet7 servers.

**Comment by def-** [comment]
@fokkonaut @ChillerDragon Should I revert back to a known good state or can you provide a fix quickly?

**Comment by fokkonaut** [comment]
ChillerDragon is not involved in my changes, and I didnt really change anything that should cause it. Can look into it later.

**Comment by def-** [comment]
I have now reverted all official servers back to 58347e877682e55b04f4aa00b1580db285acfd57

**Comment by fokkonaut** [comment]
There shouldnt be anything after that commit that causes crashes.

**Comment by def-** [comment]
Right, still crashing. I thought you said it's related to your update to vanilla master.

So I have no idea how to fix this. I guess it's better to shut down the servers if they keep crashing every few minutes.

**Comment by ChillerDragon** [comment]
@def- could you provide any information on how to reproduce? Is it a specific map? Are there any hints in the logs prior to the crash? There has to be something specific that you get crashes every 5 minutes and I do not.

**Comment by def-** [comment]
Nope, just saw it on the official servers everywhere and then reverted before the merge from vanilla and all is good since then.

**Comment by def-** [comment]
Any idea if this is fixed already?

**Comment by ChillerDragon** [comment]
@def- running full servers with ddnet7 master since months and could not reproduce this bug once. Please provide more details.

**Comment by def-** [comment]
Haven't seen this anymore since the last update.
