### ISSUE TITLE
Missing /r reply to whisper

### ISSUE THREAD

**Issue by ChillerDragon** [ddnet/ddnet7#65]
Since ddnet uses the 0.7 vanilla whisper system it would make sense to also activate the /r reply command. But yikes it would be the same as /r as in rescue. Maybe use /c converse like in 0.6?

**Comment by fokkonaut** [comment]
Yea, /r is /r, nothing to do about it. /c could be used but it wouldnt open the clientside whisper menu. Thats why I left that one open. Also, when pressing the whisper key clientside again after a whisper, you automatically select the last whispered to target from your last whisper conversation.
