### ISSUE TITLE
Only best finishes will be written in the database

### ISSUE THREAD

**Issue by trafilaw** [ddnet/ddnet7#71]
hey,

I saw that only the best finishes will be written in the database, normally it should all finishes written in the database ^^

https://i.imgur.com/VSIWCgj.png <-- Finish from Candy 89 sec on neverGores2
After I search it in the database, I didn't found it
https://i.imgur.com/HLUOjeO.png <-- This are only new records

~Law

**Comment by def-** [comment]
Thanks for the report, the code was missing.
