### ISSUE TITLE
Remove tracking of whispers in logs!

### ISSUE THREAD

**Issue by 0xcny** [ddnet/ddnet7#80]
The whisper function should be where private conversations take place. I've noticed that a lot of server admins of bigger servers like to read through the logs including the whispers. 
Imo tracking them does nothing but undermine the privacy of the players.

**Comment by edg-l** [comment]
anyone can modify the code and log whispers, dont say anything sensitive in ur whispers, or make a client with end to end encryption.

You could implement [OTR](https://en.wikipedia.org/wiki/Off-the-Record_Messaging)
