### ISSUE TITLE
too weak connection: out of buffer

### ISSUE THREAD

**Issue by def-** [ddnet/ddnet7#95]
On Vanilla client when voting for a different server type, noticed on far away servers like Chile.

**Comment by def-** [comment]
Ok, SvSendVotesPerTick is totally missing.

**Comment by def-** [comment]
Ah, it's SvVotesPerTick instead. I'll try lowering that. Not sure why it needs a different name in ddnet7 though.

**Comment by fokkonaut** [comment]
Guess because I took the initial commit
